---
# handlers file for iptables

- name: iptables restart
  service:
    name: iptables
    state: restarted
    enabled: true

#- name: iptables save
#  iptables_state:
#    state: saved
#    path: /etc/sysconfig/iptables
- name: iptables save
  command: service iptables save
  #shell: iptables-save > /etc/sysconfig/iptables

- name: sysctl setting
  command: sysctl -p /etc/sysctl.d/{{ item }}
  loop:
  - "01-forwarding.conf"

#- name: network restart redhat
#  systemd:
#    name: network.service
#    state: restarted
#    enabled: yes

- name: network restart redhat
  service:
    name: network.service
    state: restarted
  when: ansible_os_family == "RedHat"

- name: netplan apply ubuntu
  command: netplan apply
#  when: ansible_os_family == "Ubuntu"

- name: network restart debian
  shell: ifdown eth1 && ifup eth1
#  when: ansible_os_family == "Debian"

- name: nginx restart
  service:
    name: nginx
    state: restarted
    enabled: true
